// <auto-generated />
using System;
using MESDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240605050807_AddColumnStatus")]
    partial class AddColumnStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESDashboard.Models.DowntimeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DowntimeDuration")
                        .HasColumnType("time");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DowntimeReports");
                });

            modelBuilder.Entity("MESDashboard.Models.LadleCompositionData", b =>
                {
                    b.Property<string>("LadleNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Al")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("As")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ce")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Co")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("N")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Si")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("V")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Zn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LadleNo");

                    b.ToTable("LadleCompositionData");
                });

            modelBuilder.Entity("MESDashboard.Models.PipeProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LadleCompositionDataLadleNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LadleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LadleCompositionDataLadleNo");

                    b.ToTable("PipeProductionReports");
                });

            modelBuilder.Entity("MESDashboard.Models.ProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityDefective")
                        .HasColumnType("int");

                    b.Property<int>("QuantityProduced")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductionReports");
                });

            modelBuilder.Entity("MESDashboard.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MESDashboard.Models.PipeProductionReport", b =>
                {
                    b.HasOne("MESDashboard.Models.LadleCompositionData", "LadleCompositionData")
                        .WithMany("PipeProductionReports")
                        .HasForeignKey("LadleCompositionDataLadleNo");

                    b.Navigation("LadleCompositionData");
                });

            modelBuilder.Entity("MESDashboard.Models.LadleCompositionData", b =>
                {
                    b.Navigation("PipeProductionReports");
                });
#pragma warning restore 612, 618
        }
    }
}
